# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.

{
  flake.nixosModules.host-tungsten = {




  config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-7c4006b4-533d-41f3-88c5-5bc79713b1bf";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-7c4006b4-533d-41f3-88c5-5bc79713b1bf".device = "/dev/disk/by-uuid/7c4006b4-533d-41f3-88c5-5bc79713b1bf";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/E631-C3AC";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-f4bf2d83-f380-47e7-b854-3beacff91e0e"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
};
}
